force-app/main/default/objects/Transformation__mdt/Transformation__mdt.object-meta.xml
<CustomObject>
    <description>Configuration to transform one object to another e.g. JSON to/from SObject, or any other gettable/puttable pairing</description>
    <label>Transformation</label>
    <pluralLabel>Transformations</pluralLabel>
</CustomObject>

force-app/main/default/objects/Transformation_Field__mdt/Transformation_Field__mdt.object-meta.xml
<CustomObject>
    <description>A field in a Transformation</description>
    <label>Transformation Field</label>
    <pluralLabel>Transformation Fields</pluralLabel>
</CustomObject>

force-app/main/default/objects/Transformation_Field__mdt/fields/Apex_Class__c.field-meta.xml
<CustomField>
    <fullName>Apex_Class__c</fullName>
    <description>A class implementing nebc.Function to be run on values as they go from source to destination</description>
    <inlineHelpText>A class implementing nebc.Function to be run on values as they go from source to destination</inlineHelpText>
    <label>Apex Class</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Transformation_Field__mdt/fields/Source_Field__c.field-meta.xml
<CustomField>
    <fullName>Source_Field__c</fullName>
    <label>Source Field</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Transformation_Field__mdt/fields/Target_Field__c.field-meta.xml
<CustomField>
    <fullName>Target_Field__c</fullName>
    <label>Target Field</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Transformation_Field__mdt/fields/Transformation__c.field-meta.xml
<CustomField>
    <fullName>Transformation__c</fullName>
    <label>Transformation</label>
    <referenceTo>Transformation__mdt</referenceTo>
    <relationshipLabel>Transformation Fields</relationshipLabel>
    <relationshipName>Transformation_Fields</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/classes/ReverseTransformation.cls
/**
 * @author aidan@nebulaconsulting.co.uk
 * @date 17/11/2021
 * @description (if required)
 */

public inherited sharing class ReverseTransformation extends Transformation {

    public ReverseTransformation(String transformationName, Type targetType) {
        this(
        [
                SELECT Source_Field__c, Target_Field__c, Apex_Class__c
                FROM Transformation_Field__mdt
                WHERE Transformation__r.DeveloperName = :transformationName
        ],
                targetType);
    }

    @TestVisible
    private ReverseTransformation(List<Transformation_Field__mdt> transformationFields, Type targetType) {
        super(new nebc.LazySObjectIterator(transformationFields.deepClone())
                .mapValuesT(new SwapFields(Transformation_Field__mdt.Source_Field__c, Transformation_Field__mdt.Target_Field__c))
                .toList(new List<Transformation_Field__mdt>()), targetType);
    }
}